name = "lovekey-proxy"
main = "src/index.js"
compatibility_date = "2026-05-01"
account_id = "0ca12458136d4bd68dfd7b1be2769f5d"

[[kv_namespaces]]
binding = "KV_USAGE"
id = "a68452c77bfd4c9e9f176a8c9794fa82"

[vars]
OPENAI_MODEL_LIGHT = "gpt-4o-mini"
OPENAI_MODEL_HEAVY = "gpt-4.1-mini"
FREE_DAILY_LIMIT = "3"
REQUESTS_PER_MINUTE = "30"
REVENUECAT_ENTITLEMENT_ID = "pro"
