#!/bin/bash
# =============================================================================
# AI 戀愛鍵盤 - iOS Keyboard Extension Setup Guide
# =============================================================================
#
# This script documents the manual steps required to configure the keyboard
# extension target in Xcode. Modifying project.pbxproj programmatically for
# adding a new extension target is error-prone, so these steps must be done
# in Xcode directly.
#
# =============================================================================

echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║        AI 戀愛鍵盤 - iOS Keyboard Extension Setup Guide            ║"
echo "╠══════════════════════════════════════════════════════════════════════╣"
echo "║                                                                    ║"
echo "║  Follow these steps in Xcode to add the keyboard extension:        ║"
echo "║                                                                    ║"
echo "║  STEP 1: Open the Xcode project                                   ║"
echo "║  ─────────────────────────────────────────────────────────────────  ║"
echo "║  Open ios/Runner.xcworkspace in Xcode                              ║"
echo "║                                                                    ║"
echo "║  STEP 2: Add a new Keyboard Extension target                      ║"
echo "║  ─────────────────────────────────────────────────────────────────  ║"
echo "║  1. File → New → Target                                            ║"
echo "║  2. Select 'Custom Keyboard Extension'                             ║"
echo "║  3. Product Name: LoveKeyboard                                     ║"
echo "║  4. Language: Swift                                                ║"
echo "║  5. Bundle Identifier: com.ailovekeyboard.app.keyboard             ║"
echo "║  6. Click Finish                                                   ║"
echo "║  7. If prompted to activate the scheme, click 'Activate'           ║"
echo "║                                                                    ║"
echo "║  STEP 3: Replace generated files                                   ║"
echo "║  ─────────────────────────────────────────────────────────────────  ║"
echo "║  1. Delete the auto-generated KeyboardViewController.swift         ║"
echo "║  2. Drag our LoveKeyboard/KeyboardViewController.swift into the    ║"
echo "║     LoveKeyboard group in Xcode                                    ║"
echo "║  3. Replace the auto-generated Info.plist with our                  ║"
echo "║     LoveKeyboard/Info.plist                                        ║"
echo "║                                                                    ║"
echo "║  STEP 4: Configure App Groups                                      ║"
echo "║  ─────────────────────────────────────────────────────────────────  ║"
echo "║  For BOTH Runner AND LoveKeyboard targets:                         ║"
echo "║  1. Select target → Signing & Capabilities                         ║"
echo "║  2. Click '+ Capability'                                           ║"
echo "║  3. Add 'App Groups'                                               ║"
echo "║  4. Add group: group.com.ailovekeyboard.app                        ║"
echo "║                                                                    ║"
echo "║  STEP 5: Configure Build Settings                                  ║"
echo "║  ─────────────────────────────────────────────────────────────────  ║"
echo "║  For the LoveKeyboard target:                                      ║"
echo "║  1. Set Deployment Target to iOS 15.0 (or match Runner)            ║"
echo "║  2. Ensure SWIFT_VERSION = 5.0                                     ║"
echo "║  3. Set PRODUCT_BUNDLE_IDENTIFIER =                                ║"
echo "║     com.ailovekeyboard.app.keyboard                                ║"
echo "║                                                                    ║"
echo "║  STEP 6: Configure Signing                                         ║"
echo "║  ─────────────────────────────────────────────────────────────────  ║"
echo "║  For the LoveKeyboard target:                                      ║"
echo "║  1. Select your Team                                               ║"
echo "║  2. Enable 'Automatically manage signing'                          ║"
echo "║                                                                    ║"
echo "║  STEP 7: Embed the extension                                       ║"
echo "║  ─────────────────────────────────────────────────────────────────  ║"
echo "║  For the Runner target:                                            ║"
echo "║  1. General → Frameworks, Libraries, and Embedded Content          ║"
echo "║  2. Ensure LoveKeyboard.appex is listed                            ║"
echo "║  3. Build Phases → Embed Foundation Extensions should have         ║"
echo "║     LoveKeyboard.appex                                             ║"
echo "║  (This is usually done automatically when creating the target)     ║"
echo "║                                                                    ║"
echo "║  STEP 8: Test                                                      ║"
echo "║  ─────────────────────────────────────────────────────────────────  ║"
echo "║  1. Build and run on a real device or simulator                    ║"
echo "║  2. Go to Settings → General → Keyboard → Keyboards               ║"
echo "║  3. Add New Keyboard → AI 戀愛鍵盤                                 ║"
echo "║  4. Enable 'Allow Full Access' (required for network/API calls)    ║"
echo "║  5. Open any chat app, switch to AI 戀愛鍵盤                       ║"
echo "║                                                                    ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"

echo ""
echo "IMPORTANT NOTES:"
echo "  - iOS Keyboard Extensions have a ~30MB memory limit"
echo "  - 'RequestsOpenAccess' = YES is set in Info.plist for network access"
echo "  - The user MUST enable 'Allow Full Access' in Settings for the"
echo "    keyboard to make API calls"
echo "  - Data is shared between the main app and keyboard via App Groups"
echo "    using the ID: group.com.ailovekeyboard.app"
echo "  - The API key is stored in App Group UserDefaults so the keyboard"
echo "    extension can read it"
